version: '3.2'
services:
  seed:
    build: .
    environment:
      - LOGOPS_FORMAT=dev # Just for seeing nice logs.
      - ALFALFA_DB=mongodb://db:27017/seed

    depends_on:
      - db

  db:
    image: mongo:3.2
    ports:
      - "27017:27017"
